### ISSUE TITLE
Удалить геттеры

### ISSUE THREAD

**Issue by chemist-repo** [v-kyle/vue-dogs-api#1]
https://github.com/v-kyle/vue-dogs-api/blob/32a703cb2ead3547333bd158cc6a1f2d4add6cad/src/store/modules/breeds.js#L8

Геттеры нужны только если нужно как то изменить state перед выводом например отфильтровать, если изменений никаких нет то лучше использовать mapState

**Comment by v-kyle** [comment]
окей, я думал по стандарту надо использовать геттеры, а не напрямую дергать state, исправлю

**Comment by v-kyle** [comment]
https://github.com/v-kyle/vue-dogs-api/commit/63b1f6c640e9b69fcefdc5199792df3061cd432e
