### ISSUE TITLE
Не нужно оборачивать методы в функцию

### ISSUE THREAD

**Issue by chemist-repo** [v-kyle/vue-dogs-api#2]
https://github.com/v-kyle/vue-dogs-api/blob/5dcd4952c270086e655f2b66ebcda590755f24ba/src/components/ImageContainer.vue#L2

**Comment by v-kyle** [comment]
Иногда нужно, когда нужно передеать параметр из v-for, но тут да, не надо, забыл поправить при рефактиринге

**Comment by v-kyle** [comment]
а, я понял тебя, ты имеешь в виду чтобы писать сразу тело функции инлайн
ну, это как будто костыльно как-то, "красивее" передать фукнцию

**Comment by chemist-repo** [comment]
И для v-for это не нужно. Ты просто создал лишнюю функцию которая не делает ничего.

**Comment by v-kyle** [comment]
[https://github.com/v-kyle/vue-dogs-api/commit/649846484bc3a665052260d407f7e7342a3c5df4](Поправил)

**Comment by v-kyle** [comment]
[поправил](https://github.com/v-kyle/vue-dogs-api/commit/649846484bc3a665052260d407f7e7342a3c5df4)
