### ISSUE TITLE
Удалить логику добавления рандомного параметра из экшена

### ISSUE THREAD

**Issue by chemist-repo** [v-kyle/vue-dogs-api#4]
https://github.com/v-kyle/vue-dogs-api/blob/649846484bc3a665052260d407f7e7342a3c5df4/src/store/modules/breeds.js#L21

---
Это не очень красиво делать в экшене, ты можешь поместить этот option в темплейт перед циклом и убрать из экшена логику добавления random

**Comment by v-kyle** [comment]
https://github.com/v-kyle/vue-dogs-api/commit/40793e972f8799e5d5752fbb3f6dfcb60f60b5be
